# version of docker-compose
version: '3.9'
# 'services' are equivalent to 'containers'
services:
  EMAWWTEST:
    build: ./test-webapp
    # Specify an array of ports to map
    ports:
      - '80:5000'